services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - static_data:/app/staticfiles
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings

volumes:
  static_data:
